### ISSUE TITLE
Component is partially working

### ISSUE THREAD

**Issue by mindtripper** [BottlecapDave/HomeAssistant-OutlookCalendar#3]
Love the idea of this component!
And I have successfully enabled the component. It accesses the calendar, but "message" and "description" are always empty. And all_day is always false even if the event is an all day event.

By the way. "location" is populated.

State attribute example:
```
message: ''
all_day: false
start_time: '2020-03-11 16:00:00'
end_time: '2020-03-11 16:30:00'
location: 'Somewhere, Someplace'
description: ''
offset_reached: false
friendly_name: Some Name
```
Any idea why it behaves like this?

**Comment by BottlecapDave** [comment]
Hello, sorry I didn't get a chance to look at your issue.

This component has been archived in favour of https://github.com/PTST/O365-HomeAssistant. A fork of this component exists at https://github.com/BottlecapDave/O365-HomeAssistant/tree/feature/configurable-scopes which includes support for restricting access to read only to match this component.
