### ISSUE TITLE
Calendar connects well, but shows as blank

### ISSUE THREAD

**Issue by GinjNinj** [BottlecapDave/HomeAssistant-OutlookCalendar#7]
Thanks for making this, looks like it could be a great add on! 
I got it connected to my outlook account no problem (thanks for great instructions). I can see all my calendars in HA, but when I look at any of the views theyre all blank for every calendar, its like it sees the calendar but none of the items. Any ideas on a fix?

**Comment by BottlecapDave** [comment]
Hello, sorry I didn't get a chance to look at your issue.

This component has been archived in favour of https://github.com/PTST/O365-HomeAssistant. A fork of this component exists at https://github.com/BottlecapDave/O365-HomeAssistant/tree/feature/configurable-scopes which includes support for restricting access to read only to match this component.
